spring.application.name=zoo-gestion-system
server.port=8081

# Optionnel (utile en dev)
spring.thymeleaf.cache=false
logging.level.org.springframework.web=INFO

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true